LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := k80hd_bsp_fwv_512m
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM = "st7701_fwgaplus_dsi_vdo_helitai_vp531"
MTK_SECURITY_SW_SUPPORT = yes
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = yes
MTK_VERIFIED_BOOT_SUPPORT = yes
#add by guozhiliang for H405 bug 51627 2016_3_17
SAGEREAL_VIBRATE_POWERON=yes
#add by wlj for H405 bug 51627 2016_3_17
BOOT_LOGO:=fwvgaplus
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += MACH_FPGA_NO_DISPLAY
TRUSTONIC_TEE_SUPPORT=no
MTK_GOOGLE_TRUSTY_SUPPORT=no
MTK_AB_OTA_UPDATER = no
MTK_USERIMAGES_USE_F2FS = yes
MTK_DM_VERITY_OFF = yes
